name       : hunspell-sl
version    : 2018.01.04
release    : 1
source     :
    - https://extensions.libreoffice.org/extensions/slovenian-dictionary-pack/2018-01.04/@@download/file/pack-sl.oxt : ac1cf07864fc7b02bfacad601418ce3035875ebac7679e30dd7aa3dd15858619
license    :
    - LGPL-3.0-or-later
    - MPL-2.0
component  : spelling
extract    : no
summary    : Slovenian hunspell dictionary
description: |
    Slovenian spelling dictionary / Slovenski slovar za črkovanje.
setup      : |
    unzip $sources/pack-sl.oxt
install    : |
    install -Dm00644 sl_SI.{aff,dic} -t $installdir/usr/share/hunspell
